# Generated by Django 2.2.3 on 2019-11-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home_Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_background_img', models.ImageField(upload_to='media/home_page')),
                ('site_theme', models.CharField(blank=True, max_length=400, null=True)),
                ('site_description', models.CharField(blank=True, max_length=600, null=True)),
                ('call_number', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('direct_message', models.TextField()),
                ('benefit_listing_heading', models.CharField(max_length=300)),
                ('benefit_listing_description', models.TextField()),
                ('trust_listing_heading', models.CharField(max_length=300)),
                ('trust_listing_description', models.TextField()),
            ],
            options={
                'db_table': 'home page',
            },
        ),
    ]
