# Generated by Django 2.2.3 on 2019-11-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191123_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit_listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_listing_heading', models.CharField(blank=True, max_length=300, null=True)),
                ('benefit_listing_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'benefit_listings',
            },
        ),
        migrations.CreateModel(
            name='Direct_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='home_page',
            name='benefit_listing_description',
        ),
        migrations.RemoveField(
            model_name='home_page',
            name='benefit_listing_heading',
        ),
        migrations.RemoveField(
            model_name='home_page',
            name='direct_message',
        ),
    ]
