# Generated by Django 2.2.3 on 2019-11-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191123_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_page',
            name='call_to_action_statement',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
