# Generated by Django 2.2.3 on 2019-11-23 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_home_page_call_to_action_statement'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='home_page',
            table='home_page',
        ),
    ]
