# Generated by Django 2.2.3 on 2019-11-23 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191123_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Categories'),
        ),
        migrations.AlterField(
            model_name='home_page',
            name='site_theme',
            field=models.CharField(blank=True, default='Site theme', max_length=400, null=True),
        ),
    ]
