# Generated by Django 2.2.3 on 2019-11-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191123_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_page',
            name='hide_panel_statement',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
