# Generated by Django 2.2.3 on 2019-11-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20191125_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='category',
            field=models.ManyToManyField(blank=True, to='blog.Categories'),
        ),
    ]
