# Generated by Django 2.2.3 on 2019-11-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_social_media_icons_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages_from_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=600, null=True)),
                ('email', models.EmailField(blank=True, max_length=600, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=600, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'pizza',
                'db_table': 'messages_from_clients',
            },
        ),
    ]
