# Generated by Django 2.2.3 on 2019-11-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_messages_from_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Direct_Message',
        ),
        migrations.AlterModelOptions(
            name='benefit_listings',
            options={'verbose_name': 'Benefit listings'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='footer_tags_heading_text',
            options={'verbose_name': 'Footer Tags Heading Text'},
        ),
        migrations.AlterModelOptions(
            name='home_page',
            options={'verbose_name': 'Home Page'},
        ),
        migrations.AlterModelOptions(
            name='icons',
            options={'verbose_name': 'Menu Icons'},
        ),
        migrations.AlterModelOptions(
            name='messages_from_client',
            options={'verbose_name': 'Messages From Client'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='social_media_heading_text',
            options={'verbose_name': 'Social Media Heading Text'},
        ),
        migrations.AlterModelOptions(
            name='social_media_icons',
            options={'verbose_name': 'Social Media Icons'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='trust_listings',
            options={'verbose_name': 'Trust listings'},
        ),
    ]
