# Generated by Django 2.2.3 on 2019-11-28 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20191128_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit_listings',
            options={'verbose_name': 'Benefit listing'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Categorie'},
        ),
        migrations.AlterModelOptions(
            name='home_page',
            options={'verbose_name': 'Home Page', 'verbose_name_plural': 'Home Page'},
        ),
        migrations.AlterModelOptions(
            name='icons',
            options={'verbose_name': 'Menu Icon'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product'},
        ),
        migrations.AlterModelOptions(
            name='social_media_icons',
            options={'verbose_name': 'Social Media Icon'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Tag'},
        ),
        migrations.AlterModelOptions(
            name='trust_listings',
            options={'verbose_name': 'Trust listing'},
        ),
    ]
